---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: example-app
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 3m0s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/james-w3w/example-app

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta1","kind":"GitRepository","metadata":{"annotations":{},"name":"infrastructure-manifests","namespace":"flux-system"},"spec":{"interval":"1m0s","ref":{"branch":"main"},"secretRef":{"name":"flux-system"},"url":"ssh://git@github.com/w3w-internal/infrastructure-manifests.git"}}
    reconcile.fluxcd.io/requestedAt: "2022-02-04T13:41:50.424542Z"
  name: infrastructure-manifests
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 20s
  url: ssh://git@github.com/w3w-internal/infrastructure-manifests.git

