bases:
  - ../../application

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: example-deploy
        namespace: example
      spec:
        replicas: 5
    target:
      group: apps
      version: v1
      kind: Deployment
      name: example-deploy
      namespace: example

configMapGenerator:
  - name: example-config
    namespace: example
    #behavior: replace
    files:
      - configs/config.json
